steps:
- name: "gcr.io/cloud-builders/docker"
  args: ["build", "-t", "us.gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA", "."]
- name: "gcr.io/cloud-builders/docker"
  args: ["push", "us.gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA"]
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'app-chronotrack'
  - '--image'
  - 'us.gcr.io/$PROJECT_ID/${_SERVICE}:$SHORT_SHA'
  - '--region'
  - 'us-east1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- us.gcr.io/$PROJECT_ID/${_SERVICE}
