steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us.gcr.io/ramon-prd/app-chronotrack:$TAG_NAME', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us.gcr.io/ramon-prd/app-chronotrack:$TAG_NAME']
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'app-chronotrack'
  - '--image'
  - 'us.gcr.io/ramon-prd/app-chronotrack:$TAG_NAME'
  - '--region'
  - 'us-central1'
  - '--platform'
  - 'managed'
  - '--allow-unauthenticated'
images:
- us.gcr.io/ramon-prd/app-chronotrack
